/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-calendar/calendar-client/assets/dbus/com.deepin.Calendar.xml -a ./dde-calendar/toolGenerate/qdbusxml2cpp/com.deepin.CalendarAdaptor -i ./dde-calendar/toolGenerate/qdbusxml2cpp/com.deepin.Calendar.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_CALENDARADAPTOR_H
#define COM_DEEPIN_CALENDARADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-calendar/toolGenerate/qdbusxml2cpp/com.deepin.Calendar.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.Calendar
 */
class CalendarAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.Calendar")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.Calendar\">\n"
"    <method name=\"RaiseWindow\"/>\n"
"    <method name=\"OpenSchedule\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"job\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CalendarAdaptor(QObject *parent);
    virtual ~CalendarAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void OpenSchedule(const QString &job);
    void RaiseWindow();
Q_SIGNALS: // SIGNALS
};

#endif
