/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-calendar/calendar-client/src/dbus/org.deepin.dde.ControlCenter.xml -a ./dde-calendar/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenterAdaptor -i ./dde-calendar/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenter.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_CONTROLCENTERADAPTOR_H
#define ORG_DEEPIN_DDE_CONTROLCENTERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-calendar/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenter.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.ControlCenter1
 */
class ControlCenter1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.ControlCenter1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.ControlCenter1\">\n"
"    <method name=\"ShowPage\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ControlCenter1Adaptor(QObject *parent);
    virtual ~ControlCenter1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void ShowPage(const QString &url);
Q_SIGNALS: // SIGNALS
};

#endif
