/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-calendar/calendar-client/src/dbus/org.deepin.dde.ControlCenter.xml -a ./dde-calendar/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenterAdaptor -i ./dde-calendar/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenter.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-calendar/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenterAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ControlCenter1Adaptor
 */

ControlCenter1Adaptor::ControlCenter1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ControlCenter1Adaptor::~ControlCenter1Adaptor()
{
    // destructor
}

void ControlCenter1Adaptor::ShowPage(const QString &url)
{
    // handle method call org.deepin.dde.ControlCenter1.ShowPage
    QMetaObject::invokeMethod(parent(), "ShowPage", Q_ARG(QString, url));
}

